export const SUBMITFORM1 = "SUBMITFORM1";
export const SUBMITFORM2 = "SUBMITFORM2";
export const ISFOCUSEDFIRSTNAME1 = "ISFOCUSEDFIRSTNAME1";
export const ISFOCUSEDLASTNAME1 = "ISFOCUSEDLASTNAME1";
export const ISFOCUSEDFIRSTNAME2 = "ISFOCUSEDFIRSTNAME2";
export const ISFOCUSEDLASTNAME2 = "ISFOCUSEDLASTNAME2";
